version: '2'
services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
            - ../application:/var/www/application:ro
        working_dir: /var/www/application
        networks:
            - net

    php-fpm:
        # Customised image to add SIGINT trapping entrypoint as a script wrapper.
        build: php-fpm
        image: chrbrd/php-fpm
        # No longer needed with `xdebug.remote_connect_back` set to `1`.
        #environment:
        #    XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
        volumes:
            - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./config/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
            - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ../application:/var/www/application
        working_dir: /var/www/application
        networks:
            - net

    mysql:
        image: mysql/mysql-server:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_ROOT_HOST=%
        volumes:
            # Use a Docker volume instead of storing the DB data within the project structure.
            #- ./data/mysql:/var/lib/mysql
            - data:/var/lib/mysql
        networks:
            - net

volumes:
    data:

networks:
    net:
